'use client';
import {useEffect,useState} from 'react';
type Status={initialized:boolean;bridge_enabled?:boolean;fingerprint?:string;created_at?:string;csrf?:string;error?:string};
export default function SetupPanel({capabilities={posts:false,reposts:false,ownReplies:false}}:{capabilities?:{posts:boolean;reposts:boolean;ownReplies:boolean}}){
 const [status,setStatus]=useState<Status|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function load(){try{const response=await fetch('/api/service-setup',{cache:'no-store'});const data=await response.json() as Status;if(!response.ok)throw Error(data.error||'Unable to load setup');setStatus(data);setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to load setup');}}
 useEffect(()=>{void load();},[]);
 async function initialize(){if(!status?.csrf||busy||status.initialized)return;setBusy(true);setError('');try{const response=await fetch('/api/service-setup',{method:'POST',headers:{'Content-Type':'application/json','X-Setup-CSRF':status.csrf},body:JSON.stringify({action:'generate-read-only-key'})});const data=await response.json() as Status;if(!response.ok)throw Error(data.error||'Setup failed');setStatus(data);}catch(e){setError(e instanceof Error?e.message:'Setup unavailable');}finally{setBusy(false);}}
 return <><section aria-label="Connection status"><div><span>Private connection key</span><strong className={status?.initialized?'ready':''}>{status?status.initialized?'Created':'Not created':'Checking…'}</strong></div><div><span>Read-only service bridge</span><strong>{status?.bridge_enabled?'Enabled':'Pending'}</strong></div><div><span>Cached mentions &amp; posts</span><strong>{status?.bridge_enabled?'Available when configured':'Disabled'}</strong></div><div><span>Original-post frontend</span><strong>{capabilities.posts?'Enabled':'Disabled'}</strong></div><div><span>Repost frontend</span><strong>{capabilities.reposts?'Enabled':'Disabled'}</strong></div><div><span>Own-thread reply frontend</span><strong>{capabilities.ownReplies?'Enabled':'Disabled'}</strong></div></section><p>Frontend settings do not establish backend or X authorization. Publishing also requires the backend account check, durable duplicate prevention, and its separate enablement. Replies, when enabled, are limited to people directly replying to account-owned original posts, with opt-outs respected and one automated response per interaction. This page cannot enable publishing.</p>{status?.initialized?<><h2>Key created</h2><p>{status.bridge_enabled?'The read-only service bridge is enabled. Use the connection status tool to verify backend connectivity. Read tools only return existing cache.':'The public key is ready to be pinned to the existing backend. The connection remains disabled until that verification is complete.'}</p><p className="fingerprint">Public-key fingerprint<br/>{status.fingerprint}</p><p>Retries reuse this key. This page cannot rotate or reveal it.</p></>:<><h2>Create the private connection key</h2><p>When you click the button, this private Site generates a key on its server and stores it in its private database. Cloudflare encrypts the database at rest, but authorized database administrators and server code can read the key. This is not a dedicated secret vault.</p><p>The private key is never displayed or sent to the assistant. Only its public key is available for verification. Creating it does not turn on publishing; any approved publishing access uses separate server controls.</p><button disabled={!status||busy} onClick={initialize}>{busy?'Creating key…':'Generate private connection key'}</button></>}{error&&<p role="alert">{error} <button className="secondary" onClick={load} disabled={busy}>Reload setup</button></p>}</>;
}
