import { test } from 'node:test';
import assert from 'node:assert/strict';
import {handleMcp,authorize} from '../lib/x-mcp.mjs';
const owner={'oai-authenticated-user-id':'site-user','oai-authenticated-user-email':'owner@example.invalid'};
const req=(method,params={},headers={})=>new Request('https://local/mcp',{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});
test('discovery is anonymous and private-data-free',async()=>{for(const method of ['initialize','tools/list','ping']){const r=await handleMcp(req(method));assert.equal(r.status,200);const text=await r.text();assert.ok(!text.includes('owner@example.invalid'));assert.ok(!text.includes('workers.dev'));}});
test('owner identity required; no bypass token manufacture',async()=>{for(const headers of [{},{'oai-authenticated-user-email':owner['oai-authenticated-user-email']},{'OAI-Sites-Authorization':'Bearer arbitrary'}]){assert.equal((await handleMcp(req('tools/call',{name:'x_connection_status'},headers))).status,401);}assert.equal(authorize(new Headers({...owner,'oai-authenticated-user-email':'other@example.com'})),403);});
test('all data tools deny other user',async()=>{for(const name of ['x_connection_status','x_read_mentions','x_read_posts'])assert.equal((await handleMcp(req('tools/call',{name},{...owner,'oai-authenticated-user-email':'other@example.com'}))).status,403);});
test('status is accurate and never calls network',async()=>{const old=globalThis.fetch;globalThis.fetch=()=>{throw Error('Network forbidden')};try{const r=await handleMcp(req('tools/call',{name:'x_connection_status'},owner));const data=JSON.parse((await r.json()).result.content[0].text);assert.equal(data.x_connected,null);assert.equal(data.backend_connected,false);assert.equal(data.owner_authenticated,true);}finally{globalThis.fetch=old;}});
test('cached tools fail closed without backend access',async()=>{for(const name of ['x_read_mentions','x_read_posts']){const b=await (await handleMcp(req('tools/call',{name,arguments:{}},owner))).json();assert.equal(b.result.isError,true);assert.equal(JSON.parse(b.result.content[0].text).reason,'backend_service_authorization_required');}});
test('only fixed names, strict empty arguments, no caller-selected owners or URLs',async()=>{for(const [name,args]of [['x_publish',{}],['x_read_posts',{limit:21}],['x_read_posts',{limit:0}],['x_read_posts',{limit:1.5}],['x_read_posts',{url:'https://evil.test'}],['x_read_mentions',{owner:'other'}],['x_connection_status',{limit:1}]])assert.equal((await(await handleMcp(req('tools/call',{name,arguments:args},owner))).json()).error.code,-32602);});
test('malformed, batch and oversized inputs rejected',async()=>{for(const [body,status]of [['{',400],['[]',400],['x'.repeat(9000),413]])assert.equal((await handleMcp(new Request('https://local/mcp',{method:'POST',headers:{'content-type':'application/json'},body}))).status,status);});
test('connected backend reports stored unlinked X without inventing live readiness',async()=>{
 const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);
 const private_jwk=JSON.stringify(await crypto.subtle.exportKey('jwk',pair.privateKey));const public_jwk=JSON.stringify(await crypto.subtle.exportKey('jwk',pair.publicKey));
 const db={prepare(sql){return {async first(){return sql.includes('SELECT private_jwk')?{private_jwk,fingerprint:'test-only'}:{owner_id:'site-user',public_jwk,fingerprint:'test-only',created_at:'2026-10-01T00:00:00Z'}}}}};
 const old=globalThis.fetch;globalThis.fetch=async(url)=>{assert.equal(url,'https://backend.example.invalid/service/mcp');return Response.json({jsonrpc:'2.0',id:1,result:{structuredContent:{linked:false,reconnect_required:false,polling_enabled:false,post_enabled:false,reply_enabled:false}}})};
 try{const r=await handleMcp(req('tools/call',{name:'x_connection_status'},owner),db);const body=await r.json();assert.equal(body.result.isError,false);assert.equal(body.result.structuredContent.backend_connected,true);assert.equal(body.result.structuredContent.x_connected,null);assert.equal(body.result.structuredContent.x_linked,false);assert.equal(body.result.structuredContent.read_tools_contact_x,false);assert.equal(body.result.structuredContent.live_x_enabled,null)}finally{globalThis.fetch=old}
});
