import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {handleSetup} from '../lib/setup-api.mjs';
import {SITE_ORIGIN,initializeFromOwnerClick,readPublicKey} from '../lib/service-key.mjs';
const source=await readFile(new URL('../lib/service-key.mjs',import.meta.url),'utf8');
// Test-only isolated module: production remains compiled disabled.
const testSource='data:text/javascript;base64,'+Buffer.from(source.replace('SERVICE_BRIDGE_ENABLED=false','SERVICE_BRIDGE_ENABLED=true')).toString('base64');
const signer=await import(testSource);
const adapterSource=(await readFile(new URL('../lib/service-adapter.mjs',import.meta.url),'utf8')).replace("'./service-key.mjs'",JSON.stringify(testSource));
const {createServiceAdapter}=await import('data:text/javascript;base64,'+Buffer.from(adapterSource).toString('base64'));
const owner=new Headers({'oai-authenticated-user-id':'test-only-owner','oai-authenticated-user-email':'owner@example.invalid'});
function memoryDb(){let row=null;return {get row(){return row},prepare(sql){let values;return {bind(...v){values=v;return this},async run(){if(!row){const [owner_id,public_jwk,private_jwk,fingerprint,created_at]=values;row={owner_id,public_jwk,private_jwk,fingerprint,created_at}}},async first(){if(!row)return null;if(sql.includes('SELECT private_jwk'))return {private_jwk:row.private_jwk,fingerprint:row.fingerprint};const {private_jwk,...pub}=row;return pub}}}}}
async function fixture(){const db=memoryDb();await initializeFromOwnerClick(db,{id:'test-only-owner'});return db}
const setup=(method,headers={},body)=>new Request(SITE_ORIGIN+'/api/service-setup',{method,headers:{...Object.fromEntries(owner),...headers},...(body?{body}: {})});
const validHeaders=csrf=>({'origin':SITE_ORIGIN,'sec-fetch-site':'same-origin','content-type':'application/json','cookie':'__Host-dot-x-setup='+csrf,'x-setup-csrf':csrf});
test('GET setup never creates key and reveals no private field',async()=>{const db=memoryDb();const r=await handleSetup(setup('GET'),db);assert.equal(r.status,200);assert.equal((await r.json()).initialized,false);assert.equal(db.row,null);assert.match(r.headers.get('set-cookie'),/Secure; HttpOnly; SameSite=Strict/)});
test('setup rejects untrusted owner, cross-origin, CSRF, extra action',async()=>{const db=memoryDb();assert.equal((await handleSetup(setup('GET',{'oai-authenticated-user-email':'other@example.com'}),db)).status,403);const csrf=crypto.randomUUID();for(const headers of [{}, {...validHeaders(csrf),origin:'https://evil.test'},{...validHeaders(csrf),'sec-fetch-site':'cross-site'},{...validHeaders(csrf),'x-setup-csrf':'no'}])assert.equal((await handleSetup(setup('POST',headers,'{"action":"generate-read-only-key"}'),db)).status,403);assert.equal((await handleSetup(setup('POST',validHeaders(csrf),'{"action":"generate-read-only-key","owner":"evil"}'),db)).status,400);assert.equal(db.row,null)});
test('explicit test setup binds owner, returns only public material, cannot rotate',async()=>{const db=memoryDb();const csrf=crypto.randomUUID();const r=await handleSetup(setup('POST',validHeaders(csrf),'{"action":"generate-read-only-key"}'),db);assert.equal(r.status,200);const pub=await r.json();assert.equal(pub.initialized,true);assert.equal(pub.public_jwk.d,undefined);assert.equal(pub.private_jwk,undefined);assert.equal(db.row.owner_id,'test-only-owner');const old=db.row.private_jwk;await initializeFromOwnerClick(db,{id:'test-only-owner'});assert.equal(db.row.private_jwk,old);await assert.rejects(()=>initializeFromOwnerClick(db,{id:'other'}));assert.equal((await handleSetup(setup('GET',{'oai-authenticated-user-id':'other'}),db)).status,403);assert.equal((await readPublicKey(db)).private_jwk,undefined)});
test('ES256 proof verifies with public key and exact contract',async()=>{const db=await fixture();const proof=await signer.fixedServiceRequest(owner,db,'x_connection_status');const [h,p,s]=proof.authorization.slice(7).split('.');const header=JSON.parse(Buffer.from(h,'base64url'));const claims=JSON.parse(Buffer.from(p,'base64url'));assert.deepEqual(Object.keys(header).sort(),['alg','kid','typ']);assert.equal(header.alg,'ES256');assert.equal(header.typ,'JWT');assert.equal(header.kid,db.row.fingerprint);assert.deepEqual(Object.keys(claims).sort(),['iss','sub','aud','scope','iat','exp','jti','method','path','body_sha256'].sort());assert.equal(claims.iss,signer.SITE_ORIGIN);assert.equal(claims.sub,signer.SERVICE_SUBJECT);assert.equal(claims.aud,signer.ENDPOINT);assert.equal(claims.scope,'x:read');assert.equal(claims.exp-claims.iat,45);assert.equal(Number.isInteger(claims.iat),true);assert.match(claims.jti,/^[a-f0-9-]{36}$/);assert.equal(claims.method,'POST');assert.equal(claims.path,'/service/mcp');assert.equal(claims.body_sha256,await signer.digest(proof.body));assert.equal(Buffer.from(s,'base64url').length,64);const key=await crypto.subtle.importKey('jwk',JSON.parse(db.row.public_jwk),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);assert.equal(await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,Buffer.from(s,'base64url'),Buffer.from(h+'.'+p)),true)});
const status={linked:false,reconnect_required:false,polling_enabled:false,post_enabled:false,reply_enabled:false};
const response=value=>Response.json({jsonrpc:'2.0',id:1,result:{structuredContent:value}});
test('fixed endpoint, no forwarded owner/bypass headers and no extra args',async()=>{const db=await fixture();let calls=0;const a=createServiceAdapter({db,fetchImpl:async(url,init)=>{calls++;assert.equal(url,signer.ENDPOINT);assert.equal(init.redirect,'manual');assert.deepEqual(Object.keys(init.headers).sort(),['Accept','Authorization','Content-Type','MCP-Protocol-Version'].sort());assert.deepEqual(JSON.parse(init.body).params,{name:'x_connection_status',arguments:{}});return response(status)}});assert.deepEqual((await a.call(owner,'x_connection_status')).value,status);for(const [h,n,args] of [[new Headers(),'x_read_posts',{}],[owner,'x_write',{}],[owner,'x_read_posts',{url:'https://evil.test'}]])assert.equal((await a.call(h,n,args)).ok,false);assert.equal(calls,1)});
test('failures are bounded and sanitized; malformed responses rejected',async()=>{const db=await fixture();for(const r of [new Response('private detail',{status:403}),new Response('x'.repeat(65537),{headers:{'content-type':'application/json'}}),response({...status,private:'secret'}),response({records:Array(21).fill({id:'1',text:'x'}),fetched_at:null,stale:true,pending_pages:false})]){const a=createServiceAdapter({db,fetchImpl:async()=>r});const result=await a.call(owner,'x_connection_status');assert.equal(result.ok,false);assert.ok(!JSON.stringify(result).includes('private detail'))}const a=createServiceAdapter({db,fetchImpl:()=>new Promise(()=>{}),timeoutMs:10});assert.equal((await a.call(owner,'x_read_posts')).reason,'upstream_timeout')});
test('production adapter without storage never contacts backend',async()=>{const {createServiceAdapter:production}=await import('../lib/service-adapter.mjs');const a=production({fetchImpl:()=>{throw Error('Egress prohibited')}});assert.equal((await a.call(owner,'x_connection_status')).reason,'backend_service_authorization_required')});
test('backend missing cache is explicit, never substituted by empty records',async()=>{const a=createServiceAdapter({db:await fixture(),fetchImpl:async()=>Response.json({jsonrpc:'2.0',id:1,result:{isError:true,content:[{type:'text',text:'D1_BINDING_REQUIRED'}]}})});assert.deepEqual(await a.call(owner,'x_read_posts'),{ok:false,status:503,reason:'backend_cache_not_configured'});assert.deepEqual(await a.call(owner,'x_connection_status'),{ok:false,status:503,reason:'upstream_tool_error'})});
