import {test} from 'node:test';import assert from 'node:assert/strict';
import {handleSetup} from '../lib/setup-api.mjs';
import {SITE_ORIGIN,publicInfo,fixedServiceRequest,digest} from '../lib/service-key.mjs';
import {handleMcp} from '../lib/x-mcp.mjs';
const owner={'oai-authenticated-user-id':'site-owner','oai-authenticated-user-email':'owner@example.invalid'};
const row={owner_id:'site-owner',public_jwk:JSON.stringify({kty:'EC',crv:'P-256',x:'public-x',y:'public-y'}),fingerprint:'public-fingerprint',created_at:'2026-10-01T00:00:00Z'};
function db(saved=row){return {prepare(sql){assert.ok(!sql.includes('private_jwk'));return {async first(){return saved}}}};}
const request=(method='GET',headers={},body)=>new Request(SITE_ORIGIN+'/api/service-setup',{method,headers:{...owner,...headers},...(body?{body}: {})});
const csrf='01234567-0123-0123-0123-012345678901';
const postHeaders={origin:SITE_ORIGIN,'sec-fetch-site':'same-origin','content-type':'application/json','x-setup-csrf':csrf,cookie:'__Host-dot-x-setup='+csrf};
test('anonymous, service bearer and wrong email cannot inspect or initialize',async()=>{for(const headers of [{},{'OAI-Sites-Authorization':'Bearer fake'},{...owner,'oai-authenticated-user-email':'other@example.com'}]){const r=await handleSetup(new Request(SITE_ORIGIN+'/api/service-setup',{headers}),db());assert.ok([401,403].includes(r.status));}});
test('GET reveals public metadata only; CSRF cookie protected; never generates keys',async()=>{const response=await handleSetup(request(),db());assert.equal(response.status,200);const text=await response.text();assert.ok(!text.includes('owner_id'));assert.ok(!text.includes('private'));const cookie=response.headers.get('set-cookie');for(const option of ['__Host-','Secure','HttpOnly','SameSite=Strict','Path=/'])assert.ok(cookie.includes(option));assert.equal((await handleSetup(request(),db(null))).status,200);});
test('persisted owner ID enforced even with same email',async()=>{assert.equal((await handleSetup(request('GET',{'oai-authenticated-user-id':'different-id'}),db())).status,403);const r=await handleMcp(new Request(SITE_ORIGIN+'/mcp',{method:'POST',headers:{...owner,'oai-authenticated-user-id':'different-id','content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'x_connection_status'}})}),db());assert.equal(r.status,403);});
test('CSRF, cross-origin, malformed and injected setup payloads denied',async()=>{for(const changes of [{origin:'https://evil.test'},{'sec-fetch-site':'cross-site'},{'x-setup-csrf':'bad'},{cookie:''}])assert.equal((await handleSetup(request('POST',{...postHeaders,...changes},'{"action":"generate-read-only-key"}'),db(null))).status,403);for(const body of ['{}','{"action":"generate-read-only-key","key":"attacker"}','x'.repeat(129)])assert.equal((await handleSetup(request('POST',postHeaders,body),db(null))).status,400);});
test('repeat initialization returns same public key without any generation or write',async()=>{const r=await handleSetup(request('POST',postHeaders,'{"action":"generate-read-only-key"}'),db());assert.equal(r.status,200);assert.deepEqual(await r.json(),publicInfo(row));});
test('fixed service signer fails closed before selecting private key for wrong owner',async()=>{await assert.rejects(()=>fixedServiceRequest(new Headers({...owner,'oai-authenticated-user-id':'other'}),db(),'x_read_posts'),/owner/);await assert.rejects(()=>fixedServiceRequest(new Headers(owner),db(),'arbitrary'),/owner/);});
test('fixed body digest contract uses exact bytes',async()=>{assert.equal(await digest('{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"x_connection_status","arguments":{}}}'),'Os7OObw8tqBOAuME_iFDFmZx-TYo2AhWCwzAO9hIRFI');});
test('mocked initialization is singleton and concurrent retries preserve one winner',async()=>{
 // Mock primitives only: no actual credential generated or persisted in tests.
 const original=globalThis.crypto;let saved=null,writes=0;
 const mock={randomUUID:original.randomUUID.bind(original),subtle:{digest:original.subtle.digest.bind(original.subtle),async generateKey(){return {publicKey:{},privateKey:{}}},async exportKey(){return {kty:'EC',crv:'P-256',x:'mock-public-x',y:'mock-public-y',d:'mock-not-a-key'}}}};
 Object.defineProperty(globalThis,'crypto',{value:mock,configurable:true});
 const memory={prepare(sql){if(sql.startsWith('SELECT'))return {async first(){return saved}};assert.ok(sql.includes('ON CONFLICT(id) DO NOTHING'));return {bind(ownerId,pub,priv,fingerprint,created){assert.equal(JSON.parse(priv).d,'mock-not-a-key');return {async run(){writes++;saved??={owner_id:ownerId,public_jwk:pub,fingerprint,created_at:created};}}}}}};
 try{const responses=await Promise.all([1,2,3].map(()=>handleSetup(request('POST',postHeaders,'{"action":"generate-read-only-key"}'),memory)));const values=await Promise.all(responses.map(r=>r.json()));assert.ok(responses.every(r=>r.status===200));assert.ok(values.every(v=>v.fingerprint===saved.fingerprint));assert.ok(values.every(v=>!('d'in v.public_jwk)));const before=writes;await handleSetup(request('POST',postHeaders,'{"action":"generate-read-only-key"}'),memory);assert.equal(writes,before);}finally{Object.defineProperty(globalThis,'crypto',{value:original,configurable:true});}
});
